language: csharp

matrix:
  include:
    - os: osx
      dotnet: 2.1.4
      mono: none
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell
    - os: linux
      dotnet: 2.1.4
      mono: none
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell

script:
- pwsh -c 'Install-Module InvokeBuild -Force -Scope CurrentUser; Invoke-Build'
